### ISSUE TITLE
Improve test coverage on XACML conformance test / PDP functionality

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#1]
## Description
To fully make the PDP follow the XACML 3.0 standard we need to add more conformance test. The test scenarios are already in place. Need to create tests, and fix potential problems discovered per test.

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
Input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
- What is allowed/not allowed (negative tesing)
- Validations
- Error messages and warnings
- ...

## Tasks
- [ ] Verify that this issue meets DoP (remove unused text, add missing text/parameters/labels, verify tasks).

## Specification tasks
- [ ] Test design / decide test need

## Development tasks
- [ ] Documentation (if relevant)
- [ ] Manual test (if needed)
- [ ] Automated test (if needed)
