### ISSUE TITLE
Avklare nødvendige endringer i GUI for tilgangsstyring for å støtte migrering av lenketjenester

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#142]
Hvor skal vi utføre endringer i GUI? Er det mest hensiktsmessig/effektivt å gjøre det i Altinn2 eller kan vi lage det som React komponent i Altinn3? 
Svar: noen endringer i GUI utføres i A2 og noen lages på nytt i A3

Gå gjennom og lag oppgaver for følgende views
- [x] Gi og fjerne rettigheter https://dev.azure.com/digdir/Altinn/_boards/board/t/Team%20Commodore/Stories/?workitem=62937
- [x] Legg til ny rolle https://github.com/Altinn/altinn-access-management-frontend/issues/133
- [x] Gi nye (enkelt)rettigheter https://github.com/Altinn/altinn-access-management-frontend/issues/114
- [x] Bekreft nye rettigheter https://github.com/Altinn/altinn-access-management-frontend/issues/114
- [x] Be om rettighet https://github.com/Altinn/altinn-access-management/issues/262
- [x] Se forespørsler: https://github.com/Altinn/altinn-access-management-frontend/issues/139
- [x] Godkjenne forespørsler: https://github.com/Altinn/altinn-access-management/issues/262
- [x] Avgiverliste: https://dev.azure.com/digdir/Altinn/_workitems/edit/63179 
       - Her ligger Issue i github for å flytte avgiverliste fra A2 til A3: https://github.com/Altinn/altinn-access-management-frontend/issues/173. Dette skjer ikke i forbindelse med migrering av lenketjenester)
- [x] Mine skjema og rettigheter https://dev.azure.com/digdir/Altinn/_workitems/edit/63182
- [x] Rettigheter virksomheten har hos andre: https://dev.azure.com/digdir/Altinn/_workitems/edit/63377
- [x] Klientdelegering (ikke nødvendig å endre)
- [x] Andre med rettigheter: https://dev.azure.com/digdir/Altinn/_workitems/edit/63376

### Gi og fjerne rettigheter
Hypotese: GUI endres i A2
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/826e997e-e521-4448-8f65-6563c4fa3d2e)
 
1.	Her må man liste ut 
a.	Roller i A2
b.	Enkeltrettigheter for både A2 og A3
c.	Instansdelegeringer i A2

### Legg til ny rolle
Hypotese: GUI endres i A2
 ![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/38dcd3ae-ba34-49e4-a60d-2856c781e54f)
1.	Roller hentes fra A2
2.	Når man klikker på ? så må tjenester som bruker rollen i A2 og A3 vises. 
a.	Sendes evt til nytt gui i 3.0? (det vi viser i dag er ikke så bra) 

Fjern rettigheter og roller
Hypotese: GUI endres i A2
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/83aa9e22-681a-4b50-935a-9377eff15ece)
 1.	Fjern enkeltrettighet vil slette delegeringer i A2 og A3
2.	Fjern rolle vil slette rolledelegering i A2

 
### Gi nye (enkelt)rettigheter
Hypotese: GUI lages på nytt i Altinn 3
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/e02d83dc-542e-40f4-a0dc-f6dd269b4894)
 1.	Søk etter skjema/tjeneste må liste opp tjenester fra både A2 og A3
2.	For tjenester registrert i RRR og SRR så skal man sjekke om avgiver ligger i rettighetsregisteret
3.	Her bør det legges til et filter for tjenesteeier 
4.	Vise frem tittel, tjenesteeier og rettighetsbeskrivelse
 
### Bekreft nye rettigheter
Hypotese: GUI lages på nytt i Altinn 3
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/b3c1fd23-30e5-4645-ae66-171d227bb8ac)
 1.	For A3 ressurser vises ikke operasjoner i dag
a.	Det er fortsatt ok selv om vi migrerer lenketjenester (Men vi kan ikke vente så innmari lenge før det er på plass. Blir et problem etter hvert som man migrerer skjema til A3) 
2.	Vise ikoner for hvilke operasjoner som er etterspurt for A2
a.	Er det hensiktsmessig å bruke ikoner når vi åpner for at tjenesteeier kan definere «hva som helst» som operasjoner? Erfaring tilsier at sluttbruker ikke «forstår» hvilke operasjoner ikonene symboliserer. Hvilken verdi har de - bortsett fra å være plassbesbarende? Kan det like gjerne løses med tekst i knapper som ligger under rettighetsbeskrivelse? 
i.	Hvis operasjoner skal symboliseres med ikoner – hvem skal finne/velge hvilke ikoner som skal symbolisere operasjoner i en arbeidsprosess? 
3.	For A2 ressurser vises operasjoner og man kan velge hvilke som skal delegeres. 
4.	Trenger vi kontroll mot SRR og RRR i dette vinduet (hvis vi har det i søkevinduet)? 

 
### Be om rettighet
Hypotese: GUI lages på nytt i Altinn 3
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/5f1c2ffb-3dfa-486b-9a30-f2b249f1b327)
 1.	Samme behov som i søkevindu for å delegere

 Hypotese: GUI lages på nytt i Altinn 3
 ![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/64ce7005-953e-40f1-924a-7bce507930fe)
1.	Må kunne opprette delegationrequest både for A3 og A2 ressurser
2.	Må være mulig å legge inn en melding som knyttes
3.	Må være mulig å sende varsel til tilgangsstyrer – evt skal man kunne legge inn epostadresse til den man ønsker å sende varsel til? 

### Se forespørsler: 
Hypotese: GUI endres i A2
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/dc2e089a-c202-4f9c-82fe-09bf7ea44835) 
1.	Tilgangsstyrer skal se «varselboble» uansett om forespørsel er opprettet på A2 tjenester eller A3 ressurser

### Godkjenne forespørsler: 
 Hypotese: GUI lages på nytt i Altinn 3
 ![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/72944427-f622-43bd-bf7c-2d4ec2b76560)
1.	Må vise frem tittel, eier og rettighetsbeskrivelse og operasjoner for både A2 tjenester og A3 ressurser
a.	Hva gjør vi med A3 ressurser? Er det akseptabelt å ikke vise hvilke operasjoner som er etterspurt – evt bare skrive «alle operasjoner»? 

 
### Avgiverliste

Hypotese: Endringer gjøres i A2. GUI beholdes slik det er og man kun oppdaterere hvor avgiverliste hentes fra. 

1.	Hente avgivere fra både A2 og A3
 Stort aktørvalg 
Hypotese: GUI endres i A3
 ![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/6a0c98e9-fbed-44d3-ac62-5a2398995db8)
Lite aktørvalg 
Hypotese: GUI endres i A3
  ![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/6663faed-a77a-4c6f-b5f8-debd184d9c6f)

### Mine skjema og rettigheter

Hypotese: GUI endres i A2
![image](https://user-images.githubusercontent.com/25847572/221133266-fbb0d8c9-3c9c-4b0b-9a76-e2be7691633e.png)

Antar behov for endring er omtrent de samme som når man endrer oversikt over rettigheter andre har. 

Her må man liste ut 
1. Roller i A2
2. Enkeltrettigheter for både A2 og A3
3. Instansdelegeringer i A2
4. Oppprett ny forespørsel skal sende brukeren til A3 hvor nytt GUI for opprett forespørsel lages 
5. Liste opp forespørsler for både A2 tjenester og A3 ressurser

![image](https://user-images.githubusercontent.com/25847572/221134716-0118178f-1d0e-4d93-b08d-3556f254f7b2.png)

1. når man klikker på "fjern" så skjer ingenting annet enn at man får en strek over det man skal fjerne
2. når man klikker på "ferdig" så skal det slettes roller i A2, tjenestedelegeringer i A2 go ressursdelegeringer i A3
3. det er ikke mulig å slette instansdelegeringer i A2 fra denne oversikten så den har ingen behov for endring

### Virksomheten sine forespørsler

Hypotese: 

![Image](https://user-images.githubusercontent.com/25847572/222715781-5bfe7330-efdd-492e-b8e0-126e8e42fe18.png)

### Rettigheter virksomheten har hos andre
Hypotese
![image](https://user-images.githubusercontent.com/25847572/221135608-b6ba39fb-6066-4131-b3c5-1678f4375d59.png)

Her vises en "avgiverliste" for virksomheten (som bruker representerer) 
Dette panelet vises for alle som er tilgangsstyrer, ???

Når man klikker på "se og endre rettigheter" så kommer man til oversiktsbilde for se og endre rettigheter

Denne oversikten må vise alle virksomheten har 
1. roller for i A2
2. enkelttjenestedelegeringer i A2
3. Paralellisignering 
4. enkeltinstansdelegering i A2
5. ressursdelegering i A3

Må endre slik at man slår opp mot A3 slik at man henter ut virksomheter man har fått ressursdleegering for i A3

### Klientdelegering
??

### Andre med rettigheter

![Image](https://user-images.githubusercontent.com/25847572/231985978-3e10c39e-8fe6-46bc-a566-12f66ba92542.png)

Må endre slik at man slår opp mot A3 slik at man henter ut virksomheter man har fått ressursdleegering for i A3

**Comment by sivaglen** [comment]
Analyse over nødvendige GUIendringer gjort og ligger i backlogg i dev.axure.com eller github
