### ISSUE TITLE
Authorization: Sync appsettings and configuration with values.yaml for environment deploy values

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#243]
### Description

There are missing and/or differently named appsettings/config values currently in comparison with the environment deploy values (see separate PR for updating values.yaml)

### Tasks

- [x] Remove uneccessary ResourceRegistrySettings file and add ApiResourceRegistryEndpoint  under PlatformSettings
- [x] Fix and sync naming of Api endpoints with values.yaml

### Acceptance Criterias

- [x] Stuff works when deployed to AT etc

**Comment by jonkjetiloye** [comment]
Deployed and tested authorization based on system-resource registered in the resource-registry
