### ISSUE TITLE
Replay functionality of delegation events in platform authorization

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#266]
### Description

Currently app-delegations are performed in platform-authorization through internal API integration with the Altinn 2.0 SBL solution.

Delegation events in platform-authorization is then pushed back to Altinn 2.0 for an eventual consistency of delegations in both platforms.

With a current downtime in the delegation event function tasked with picking up events and pushing to Altinn II it's evident that we are missing some monitoring as well as support for replaying events in order to regain consistency when/if events are lost.

### Tasks

- [x] PostgreSQL function to retrieve delegation changes for a range of change event ids
- [x] Internal API and service implementation get delegation changes, map to events and pushing to the existing delegation event queue
- [x] Function for manual execution/triggering for a specified range of change event ids
- [ ] Setup missing monitoring of existing delegation event queue for when messages are not being picked up
- [x] Setup missing deploy failure routine for existing delegation event function

**Comment by jonkjetiloye** [comment]
Replay function deployed and verified. Missing event replayed for sync with SBL in all AT environments, TT02 and Prod
