### ISSUE TITLE
POC of new authorization architecture

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#30]
### Description

To verify the [future authorization architecture](http://docs.altinn.studio/technology/architecture/components/application/solution/altinn-platform/authorization/#altinn-authorization---future),  Altinn/altinn-authorization#23  we will perform a POC.

The POC will seek to verify the core concept of some of the components.

![image](https://user-images.githubusercontent.com/13309071/185088743-9d485435-aae5-47da-b359-d8c69b06ead2.png)

### Access Group component

Over time access groups will replace Altinn roles. Access groups will be hierarchical and have a tree of groups. 

The goal for this POC

- Setup and deploy base component
- Verify data structure
- The team gets to know PostgreSQL 

See more detailed goals in Altinn/altinn-access-groups#3 

### Altinn Resource Registry

The goal for this POC 

- Setup and deploy base component
- Design and implement API
- Get to know Cosmos DB

See more detailed goals in Altinn/altinn-resource-registry#20 

### Additional Information

We need to identify which environment we should use.

What do we need from the infrastructure team? 

Is there any frontend task related to this? 

###  Preparation tasks
- [x] Move authorization component to authorization repository
- [x] Update pipeline to use new repository for deploy
- [ ] Identify which environment we will use for POC
- [ ] Present POC and new architecture for the architecture board 
- [ ] Identify needs for support by infrastructure
- [ ] Create a PostgreSQL database to be used in the correct AT environment
- [ ] Create document DB to be used in AT environments
- [ ] Identify other needs for support (pipelines)
- [ ] Identify needs for API management changes
- [ ] Identify needs for LinkerD changes
- [ ] Identify task needed to be performed before POC start that will improve efficiency

### Acceptance Criteria

- [ ] New policy component deployed and verified Altinn/altinn-authorization#29 
- [ ] New resource registry deployed and verified Altinn/altinn-resource-registry#20 
- [ ] New Access Group component deployed and verified Altinn/altinn-access-groups#3 
- [ ] PDP integrated with POC access group component Altinn/altinn-authorization#31 
- [ ] PDP integrated with Altinn Policy component Altinn/altinn-authorization#32 
- [ ] Deploy test app with access groups requirements
- [ ] Able to verify test app.

**Comment by TheTechArch** [comment]
POC complete. Working on final product
