### ISSUE TITLE
Integrate PDP with Digitalt Dødsbo as external authorization source

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#343]
### Description

Digitalt Dødsbo is to be introduced as a new external authorization source in Altinn Authorization.

This will include: 
- Introduction of a new subject xacml attribute: `urn:digitaltdodsbo:rolecode` to be used in both XACML policies and requests (added to constants)
- Implementation of a policy subject analyser to identify required subject context enrichment for decision evaluation
- Implementation of a OED context handler for enrichment of the request with roles the authenticated user has for the reportee

Clarifications needed:
- Authorization needed for OED PIP API (assume maskinporten scope authorization?)
  - Will require implementation of a maskinporten client for getting token for PIP API access

### Additional Information

OED PIP Swagger doc:
https://oed-test-authz-app.azurewebsites.net/swagger/index.html

OED Authz repository:
https://github.com/data-altinn-no/oed-authz/

Draft/WIP PR from OED with suggestions for a OED context handler:
https://github.com/Altinn/altinn-authorization/pull/265/files

POC branch for same idea of analyzing policy subject for selecting external authorization source in context of Altinn.AccessGroups:
https://github.com/Altinn/altinn-authorization/compare/main...feature/poc_integrate_pdp_accessgroups

### Tasks

- [x] OED PIP Client
- [x] Maskinporten Token Client
- [x] Policy Subject Analyser
- [x] OED Context Handler
- [x] OedAuthzMaskinportenClientSettings config for values.yaml and KeyVault secret for JWK
- [x] Add helper method to ABAC XacmlPolicy object for getting Attribute dictionary for a given Category

### Acceptance Criterias

Gitt at bruker har forumesfullmakt for en død person i digitalt dødsbos representasjonsregister
Når bruker prøver å åpne en instans av digitalt dødsbo for den døde personen
Så skal bruker autoriseres til det.

**Comment by sivaglen** [comment]
@elsand - kan du se over akseptansekriterer.

**Comment by jonkjetiloye** [comment]
Support for external decision requests using external identifiers as SSN will need to be implemented in a separate issue and endpoint:
https://github.com/Altinn/altinn-authorization/issues/448

**Comment by rtafj** [comment]
@jonkjetiloye @TheTechArch 
I roadmap-issue for digitalt dødsbo (https://github.com/digdir/roadmap/issues/189) har jeg kommentert at feature toggle gjenstår - er det gjort? Jeg har satt roadmap som levert for å rydde unna støy i statusrapportene for modernisering av Altinn, men det gjenstår å få finansiering til tjenesten, samt bruksvilkår for informasjonen vi får fra DA - det har jeg opprettet eget issue for i boardet til tilgangsstyring.
