### ISSUE TITLE
Flytte kopi av ER og FREG fra Altinn 2 til Altinn 3

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#356]
## Overordnet beskrivelse 

Altinn har i dag en egen kopi av ER og FREG som er svært sentral for mye funksjonalitet i Altinn (pålogging, autorisering, preutfylling, varsling, osv) . Kopien holdes oppdateres gjennom batchintegrasjon mot ER og ved bruk av eventlogg hos FREG
Denne kopien og integrasjon mot ER og FREG må flyttes fra Altinn 2 til Altinn 2

## Beskrivelse av løsning
Brønnøysundregistrene utvikler nå en ny løsning for Enhetsregisteret (dokumenteret på [brreg.github.io](https://brreg.github.io/docs/informasjonsmodeller/enhetsregisteret/)), antagelsen pr nå er derfor at man bør starte med FREG først. 
OPPDATERT: integrasjon mot gammel ER er større ytelsesmessig belastning, så vi starter med å flytte ER. Vi må uansett flytte ER før BR er ferdig med hele sin nye registerplattform, men hypotesen er at vi kan begrense første del til det vi trenger.

Dagens integrasjon mot FREG er forholdsvis ny og man kan anta at ny løsning kan bygge på samme konsept. 
Integrasjon mot ER er av eldre dato. I tillegg så jobber BRREG med ny løsning for sine registersystem. Det er derfor antatt at det vil være en del endringer på vår integrasjon mot de i Altinn 3. 

## Folkeregisteret
I forbindelse med migrering av FREG fra Altinn 2 til Altinn 3 vi man vurdere muligheten for å ta i bruk to nye typer representasjonsforhold
1) nye og granulerte vergemålene 
2) foreldreansvar

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-access-groups/issues/13
- [ ] https://github.com/Altinn/altinn-register/issues/171
- [ ] https://github.com/Altinn/altinn-register/issues/189
```

**Comment by rtafj** [comment]
Enhetsregisteret gjør endringer i måten de registrerer og tilgjengeliggjør opplysninger om rolleinnehavere som fratrer, dør eller slettes. Fra 10.juni 2024 vil det komme endringer på ENK (andre org.former følger etterhvert som de flyttes til ny registerplattform) som beskrevet her;
**Fratrådt (egenfratreden**)
Pliktige roller: Opplysninger om hvem som er rolleinnehaver fjernes, og det registreres en påtegning om at rolle er fratrådt
Ikke-pliktige roller: Opplysninger om rolle utgår (fjernes)

**Død person**
Pliktige roller: Personopplysninger om rolleinnehaver fjernes, og det registreres en påtegning på rollen, som viser at rolleinnehaver er død
Ikke-pliktige roller: Opplysninger om rolle utgår (fjernes)

**Slettet virksomhet**
Pliktige roller: Opplysninger om rolleinnehaver fjernes, og det registreres en påtegning på rollen, som viser at rolleinnehaver er slettet. (Ikke relevant for enkeltpersonforetak).
Ikke-pliktige roller: Opplysninger om rolle utgår (fjernes)

For pliktige roller vil dere motta tekst med informasjon om hva som har skjedd med rolleinnehaveren som påtegning. Batch ajourhold tilpasses slik at registrert påtegning vises på enkeltpersonforetak. 
(https://github.com/Altinn/altinn-support-private/issues/2631)

**Comment by annerisbakk** [comment]
@rtafj Sjekker denne. Noe merkelig med Epicen i roadmap som er lukket.

**Comment by annerisbakk** [comment]
Lukkes. Følges opp på https://github.com/Altinn/altinn-register/issues/214
