### ISSUE TITLE
Klargjøre Altinn 3 for migrering av lenketjenester

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#370]
@sivaglen commented on [Tue Jan 10 2023](https://github.com/Altinn/altinn-roadmap/issues/63)

# Overordnet beskrivelse av behov
Altinn 3 skal klargjøres slik at tjenesteeier kan migrere lenketjenester fra Altinn 2 til Altinn 3 i løpet av Q3 2023

Løsningen vil ta høyde for at lenketjenester kan migreres èn og èn. 
Ekisterende API for autorisasjon må støtte at det i en overgangsfase finnes lenketjenester som kjører på både Altinn 2 og Altinn 3 plattformen. 

```[tasklist]
### Analyseoppgaver
- [ ] https://github.com/Altinn/altinn-authorization/issues/142
- [ ] https://github.com/altinn/altinn-authorization/issues/108
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/78
- [ ] https://github.com/Altinn/altinn-authorization/issues/143
- [ ] https://github.com/Altinn/altinn-authorization/issues/144
- [ ] https://github.com/Altinn/altinn-access-management/issues/255
```

#### Målsetning
Legge til rette for at man kan begynne å ta i bruk nye API uavhengig av hvor lenketjenester kjører.
Starte migrering av lenketjenestger som ikke er avhengig av funksjonalitet som leveres i versjon 2

#### in scope
Denne endringer vil innebære at det utvikles støtte for følgende i Altinn 3 plattformen
- delegering av enkeltressurser 
  - Nytt GUI for delegering av A3-enkeltressurser og A2-enkeltrettigheter 
    - Uklart om dette også inkluderer nytt GUI for avgiverliste i A3
  - Nye API som håndterer at lenketjenester KAN være migrert fra A2 til A3 (ref API strategi)
      - inkl nye api for avgiverliste for sluttbrukersystem og tjeensteeier
- tilby frontend for å registrere ressurser og tilhørende policy i Altinn Studio 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-access-management/issues/362
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/130
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/130
```

#### Målsetning
Legge til rette for at alle lenketjenester kan migreres fra A2 til A3

#### in scope
- Flytte funksjonalitet for "forespørsel om rettighet" fra A2 til A3. (DelegationRequest). 
   - Krever nytt GUI i A3 og API for tjenesteeiere og sluttbrukere (https://github.com/Altinn/altinn-access-management/issues/332) 
- Funksjonalitet for tjenesteeier å kunne styre hvem som kan benytte en tjenesteressurs (Tjenesteeierstyrt rettighetsregister), https://github.com/Altinn/altinn-resource-registry/issues/131
  - Tilby GUI i studio for registereing av RRR? 
  - Videreutvikle sortering/søk i GUI for enkeltdelegering/delegationforespørsel slik at de kan sortere bort SRR/RRR tjenester i delegeringssammenheng

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/131
- [ ] https://github.com/Altinn/altinn-access-management/issues/363
```

### Senere
- avvikle funksjonalitet for lokale roller. Dette gjøres når tilstrekkelig mange nok tjenester er flyttet ti A3 slik at lokale roller i A2 ikke har noen verdi lengre

# Overordnet beskrivelse av løsning

-Tilby GUI for å registrere og oppdatere A3 ressurser i Ressursregister inkl policyregler https://github.com/Altinn/altinn-resource-registry/issues/78
- Nødvendige endringer i GUI for å støtte migrering av lenketjenester èn og èn til A3 https://github.com/Altinn/altinn-authorization/issues/142
  - a) Inkl å forbedre søkevindu for å finne tjenester (delegering og delegationrequest). Filter for tjenesteeier, sortere bort SRR/RRR tjenester, søk i tittel, rettighetsbeskrivlese
- Nødvendige endringer i API for å støtte migrering av lenketjenester èn og èn til A3 https://github.com/Altinn/altinn-authorization/issues/143
Avskaffe lokale roller i A2. Evt vurdere behovet på nytt etter at Nøtt og nye tilgangsgrupper er lansert. https://github.com/Altinn/altinn-authorization/issues/144

# Spørsmål
- Funksjonalitet for å registrere forespørsel om rettighet til en tjenesteressurs (DelegationRequest)
- Tilby funksjonalitet for å registrere DelegationRequest i A3 for A3 ressurser. https://github.com/Altinn/altinn-access-management/issues/332
- Tilby funskjonalitet for å registrere ResourceownerRightRegister på ressurser i A3.
  - inkl å kunne sortere bort SRR/RRR tjenester i delegeringssammenheng

Se [her](https://github.com/altinn/altinn-authorization/issues/108) for mer informasjon

**Comment by sivaglen** [comment]
Denne er duplikat av https://github.com/Altinn/altinn-authorization/issues/371
