### ISSUE TITLE
PDP Endpoint for external usage

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#448]
### Description

We need to expose a PDP endpoint for external usage. The current endpoint only supports internal consumer

### Additional Information

We should not support XML requests. Only the XACML JSON profile should be supported for the external endpoint. This makes it possible to describe the input in swagger. 

PDP will be added to AccessManagement product in APIM together with AccessManagement

### Tasks

```[tasklist]
### Clarifications
- [ ] What about SLA. Should this be added to the product in APIM with some rules? 
- [x] Support for SSN should only be supported through the new endpoint, and not affect the existing internal endpoint (which is only "protected" by subscription key)
- [x] Define attributeID for ssn and organization
```

Following is decided
urn:altinn:person:identifier-no
urn:altinn:organization:identifier-no

https://github.com/Altinn/altinn-authorization/blob/feature/externalpdp/src/Authorization/Constants/XacmlRequestAttribute.cs

```[tasklist]
###  Development Tasks 
- [x] Setup new endpoint with mapping to the internal data model
- [x] Setup scope validation
- [x] Setup integration tests in XUNIT
- [ ] Setup APIM config
- [ ] Define product for PDP in APIM
```

```[tasklist]
### Acceptance Criterias
- [x] Dont expose internal ABAC entities on API. Define duplicates in Component
- [x] Support only JSON
- [x] Require scope for usage and authorization
- [x] Support external identifiers as SSN
- [x] Swagger documentation includes XACML Json profile description
- [x] Support authorization of access to resources in the resource registry
- [x] Support authorization of access to apps
```

**Comment by Nyeng** [comment]
Rullet ut i at og prod, noe usikker på om det er tatt i bruk
