### ISSUE TITLE
Implement event log for authorization

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#461]
### Description

Altinn3 processes various types of authorization requests. Each request must be logged as an authorization event tagged with an event type. Event log request will be sent by authentication/authorization components and the event is logged by audit log api. 

Implement the logging in authorization component

### Tasks

- [x] Implement  event log for authorization requests
- [x] Restructure and update the datatypes in the authorization event table to support lookup
- [x] update the models in the authorization and audit log components

### Acceptance Criteria

- [ ] Event is logged for each authorization event
