### ISSUE TITLE
Iteration 2-Update authorization event log implementation

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#520]
### Description

Following feedback is registered after the QA of the event log in authorization

- Introduce lookup table for decision
- Remove identity field
- Include sessionid column
- Remove timetodelete

### Tasks

- [x] Update authorization event model
- [x] Update eventlogger mapping
- [x] Update unit tests

### Acceptance Criteria

- [ ] Authorization event model is updated
- [ ] Authorization event implementation is updated
- [ ] Authorization event is saved to the database
