### ISSUE TITLE
Analysis : Limit logging authorization events/authorization calls from app

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#554]
### Description

Logging QA discussion raised concerns about several calls to authorization component from the altinn 3 apps which also leads to enormous authorization event logging for a single application. A discussiuon is needed to agree on what we must log. Following points were raised during discussion

- Should we implement caching in authorization component when there are too many calls in a second(s)? If so what will be the time limitaiton here?
- Should app implement any caching self to avoid too many calls to authorization component?
- Should log component log based on the time instead?

### Tasks

- [x] Analyse 

### Tasks after Analysis

- [x] Implement check such that multirequest is not logged
- [x] Test if multirequest is not logged

### Acceptance Criteria

- [x] A solution is described to avoid too many logging for the same operation
