### ISSUE TITLE
Flytte delegerbare API ressurser fra 2.0 til autorisasjon 3.0

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#59]
Status: 
Løsning er produksjonsatt og tjenester er flyttet i TT-miljø. 
Tjenester forventes flyttet i produksjonsmiljøet innen utgangen av mai. 

### Description

Som første tjenestetype ønsker vi å flytte tjenester av typen "Delegerbare API ressurser" fra 2.0 til 3.0 plattformen. Ettersom det gjelder forholdsvis få tjenester og med kun Maskinporten som konsument av API så er caset begrenset i omfang og risiko. Samtidig vil det gi oss mye nyttig erfaring som vi kan bygge på videre når vi skal gå i gang med å flytte andre tjenestetyper. 

### Om tjenesten
Delegerbare API ressurser representerer tilgang til en API som styres gjennom maskinporten. Via maskinporten sier API-eier hvilke konsument-organisasjonser som har tilgang til deres API. I Altinn kan disse konsumentene delegere tilgang til API videre til sine systemleverandører. Resultatet er at Systemleverandør kan logge på maskinporten med sitt eget virksomhetssertifikat men få tilgang til API på vegne av konsumenten. 

![image](https://user-images.githubusercontent.com/25847572/190086564-8eb5dd6c-4347-4bb5-86f4-4fbb657a454a.png)

I Altinn er Delegerbare API-ressurser registert som tjenestetype "delegationScheme". Det finnes et eget API i Altinn 2 for å opprette Delegerbare API-ressurser (DelegationScheme) og for å spørre om hvilke delegeringer som er registert. 
En Delegerbar API-ressurs  registreres i Altinn av APIleverandøren via REST (delegationscheme). 
Det er bare Maskinporten, Norsk Helsenett og mulighens SKE som bruker REST-API for å hente ut delegeringer (delegations)

Dokumentasjon av løsningen i 2.0 finnes her: https://altinn.github.io/docs/utviklingsguider/api-delegering/
Dokumentasjon av Delegation-scheme API finnes her: https://www.altinn.no/maskinporten-api/swagger/ui/index

Det finnes i dag ca 62 registrerte tjenester av typen "Delegerbare API-ressurser" i 2.0
Det er gjort ca 7500 enkeltrettighetsdelegeringer på tjenester av typen "Delegerbare API ressurser". 

#### Roller knyttet til delegerbare API-ressurser
Rollene som knyttes til en delegerbar APIressurs er i dag hard-kodet til følgende roller:

- Bestyrende reder (BEST)
- Bostyrer (BOBE)
- Daglig leder / administrerende direktør (DAGL)
- Deltaker med delt ansvar (DTPR)
- Deltaker med fullt ansvar (DTSO)
- Innehaver (INNH)
- Komplementar (KOMP)
- Styrets leder (LEDE)
- Norsk representant for utenlandsk enhet (REPR)
Se også https://altinn.github.io/docs/utviklingsguider/api-delegering/tilgangsstyrer/#hvem-kan-delegere---rollekrav
Det er ikke mulig å overstyre dette fra apiet i dag. 

Enten må en som har rollen Hovedadministrator eller en av rollene over delegere den videre til den som trenger tilgangen.

### Hva skal gjøres
Vi skal flytte tjenester av typen "Delegerbare API ressurser" fra 2.0 til 3.0 plattformen. 
 
Vi skal samtidig tilby nye API i 3.0 for disse. Vi må avklare mot Maskinporten om de kan ta nye API i bruk med en gang eller om vi skal lage en Proxy som de kan benytte frem til de får gjort nødvendige endringer i sine spørringer. 
Samtidig som at tjenestene flyttes skal også registrerte delegeringer flyttes fra 2.0 til 3.0 slik at sluttbruker ikke påvirkes og må gjøre delegeringer på nytt selv om tjenesten flyttes. 

Det er ønskelig å opprette en ny tilgangsgruppe for Delegerbare Maskinport API-ressurser i 3.0 som i tillegg til dagens ER-roller og Hovedadministrator skal ha rettighet til å delegere tilgang til API på vegne av konsumenten til systemleverandører. Det skal lages et nytt panel i Profil for administrering av tilganger til API-ressurer. Panelet skal utvikles på 3.0. 

![image](https://user-images.githubusercontent.com/25847572/190095780-84d17928-f1a1-4a3b-bcff-4ce1da94df10.png)

 

### In scope

- Mulig å registrere en ressurs som "Delegerbar API-ressurs" med utgangspunkt i en som finnes fra før i 2.0 (#60 ) 
- Mulig å registere Autorisasjonsregler til ressusene som kan henvise til 2.0 roller og ER roller (#61) 
- Migrere/flytte registrerte enkeltdelegeringer på 2.0 tjenesten fra 2.0 til 3.0 (#62)
- API for å registrere/endre Delegerbar API-ressurs. (#63)
  - Disse benyttes i dag av alle tjenesteeiere som har delegerbare API-ressurser
- Lage en løsning for å registrere/editere ressursene i 3.0. (#64) 
  - Dette kan være at tjenesteeier sender informasjon til oss og vi registrere dette via API eller at vi lager et GUI mot Ressursreigster slik at tjenesteeeier kan registrere selv. 
- API for å hente ut informasjon om delegeringer på Delegerbar API-ressurs. (#65)
  - Disse benyttes i dag av Maskinporten, Norsk Helsenett (?) og Skatteetaten (??)) 
- Etablere nytt panel i profilen for å administrere tilgang til "Delegerbare API-ressurer" (#66)

- Automatiserte tester (i K6 eller Cypress) som tester API (#67)
- Lage plan for å flytte alle Delegerbare API-ressurser (#68) 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] https://github.com/Altinn/altinn-authorization/issues/60
- [ ] https://github.com/Altinn/altinn-access-management/issues/172
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/40
- [ ] https://github.com/Altinn/altinn-authorization/issues/64
- [ ] https://github.com/Altinn/altinn-authorization/issues/61
- [ ] https://github.com/Altinn/altinn-authorization/issues/62
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/77
- [ ] https://github.com/Altinn/altinn-authorization/issues/65
- [ ] https://github.com/Altinn/altinn-authorization/issues/66
- [ ] https://github.com/Altinn/altinn-authorization/issues/67
- [ ] https://github.com/Altinn/altinn-authorization/issues/68
- [ ] https://github.com/Altinn/altinn-authorization/issues/331
```

**Comment by sivaglen** [comment]
Status: Gjenstår å få på plass deploy-infrastruktur for BFF i produksjon. Planen er å foreta flytting av Delegationschemes i prod i uke 24 eller 25.
