### ISSUE TITLE
Add support for authorization of org users

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#7]
## Description

In some scenarios, the application owner wants to give access to one or more specific enterprises. An example is Digitale Helgeland which wants to give the municipalities access to data by defining that the specific org numbers have read access to instances

## Considerations
- PDP needs to have the possibility to check this.
- 

## Acceptance criteria

- [ ] It is possible to define that a given org number has access to an instance. 

## Development tasks

- [ ] Update role API to support org having roles for orgs
- [ ] Update Bridge to expose API
- [ ] Update context handler to understand when to ask for organizations roles
- [ ] Update role definition and API to have a list of roles 

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
This issue sounds like the service owner controlled access register in Altinn 2.

**Comment by sivaglen** [comment]
@TheTechArch er dette en issue som inngår i arbeid med å opprette RRR i altinn 3? 
Er det hensiktsmessig å beholde denne Epic og rename - eller skal vi lukke/slette denne og lage ny når vi begynner med oppgaven i forbindelse med migrering av samtykketjenester?

**Comment by FinnurO** [comment]
Skatt har også nevnt en whitelist i en sine saker?

**Comment by TheTechArch** [comment]
@sivaglen nei, det er ikke det.  Jeg foreslår at vi lukker denne. Digitale Helgeland ble løst på en annen måte og det var skepsis om å tilby dette.
