### ISSUE TITLE
Automate nuget package publishing

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#756]
### Description
We publish Altinn.Common.PEP, ABAC as nuget packages. This is done manually and also lacks changelog related to a package.
To regulate this, we will automate the nuget package publishing and release notes.

### Tasks
- [x] Create/update release notes with nuget package version
- [x] Create github action to publish nuget package on publishing of release

### Acceptance Criteria

- [ ] Nuget package publishing is automated
- [ ] Release notes/changelog is published automatically

**Comment by Nyeng** [comment]
Lukkes etter refinement
