### ISSUE TITLE
Refactor PEP for x-forwarded-for header

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#814]
### Description
Currently, PEP package has a httprequest helper method that retreives the forwarded for header and adds it to the authorization api client. App team would like that we hide the implementation complexities of the client.

### Tasks
- [x] Analyse the use of decision helper and authorization api client
- [x] Refactor the x-forwarded-for implementation in PEP

### Acceptance Criteria

- [x] Code is refactored

**Comment by Nyeng** [comment]
Lukker den etter refinement.
