### ISSUE TITLE
PEP | Add support for system user

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#921]
### Description

We need to add support for system user in PEP package.  Current package does only support organizations and end users. 

### Additional Information

The token contains systemuserID

### Tasks

- [ ] Expand mock token util to create system token matching the tokens from maskinporten
- [ ] Extend PEP to handle new token including util methods made available in PEP package
- [ ] Add unit test for this
