### ISSUE TITLE
Rutine for bestilling av API tilganger for Altinn 3

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-authorization#993]
Ref support-sak https://github.com/Altinn/altinn-support-private/issues/3081
Det må lages en rutine for håndtering av bestillinger av API tilganger for Altinn 3, og beslutning om hvem som skal ha tilganger til å utføre dette i test og produksjon. 

Kommentar fra Jon Kjetil i support-saken: 

Jeg har bare tilgang til å legge de til i Test Samarbeidsportalen for scopene:
altinn:accessmanagement/authorizedparties.resourceowner
altinn:authorization/authorize
som gir tilgang autorisasjon sine nye tjenesteeier API på Altinn 3 ([AuthorizedParties](https://docs.altinn.studio/api/accessmanagement/resourceowneropenapi/#/Authorized%20Parties/post_resourceowner_authorizedparties) og [Authorize](https://docs.altinn.studio/api/authorization/spec/#/Decision/post_authorize)).
Jeg har ikke tilgang til å kunne:
Opprette Subscription Key i Test
På autorisasjon er det vel bare 
[@Rune T. Larsen](https://digdir.slack.com/team/U078QSZB62Z)
 som har mulighet til dette nå
Opprette Subscription Key i Prod
På autorisasjon er det vel bare 
[@Rune T. Larsen](https://digdir.slack.com/team/U078QSZB62Z)
 som har mulighet til dette nå
Gi tilgang Scope i Samarbeidsportalen i Prod
På autorisasjon er det vel bare 
[@Ragnhild Tafjord](https://digdir.slack.com/team/U02QG53TX53)
 som har nødvendig tilgang

Teknisk knytt til APIM løsningen og tilganger må vi vel Platform inn i bildet ja.
Merkantilt må vel Juridisk inn i bildet.
Rutinemessig må vel ServiceDesk inn i bildet, sammen med produktteamene så dokumentasjon av API og nødvendige tilganger henger sammen så de som bestiller forstår hva de trenger, og ServiceDesk (dersom det er de som skal tildele scopes) ikke gir feil eller for brede API tilganger.

![Image](https://github.com/user-attachments/assets/9115a390-4a9a-45c5-9dd0-126bd90af589)

```[tasklist]
### Tasks
- [x] 1 Møte med servicedesk
- [x] Avklare nødvendig informasjon i en API bestilling - Møte Espen
- [x] Avklare innhold API pakker - APIM og bundling per produkt - Møte Eirik avlyst/henviser til Vemund
- [x] Avklaringsmøte Torkel/Kundeteam rundt videre arbeid avholdt 14.10.24
```

Etter møte med Torkel/kundeteam overtar kundeteamet denne oppgaven. Vi har delt de funn som vi har gjort og torkel tar dette vdere sammen med Lars Vegard med fler. Vi lukker saken i vår backlog, så vil videre arbeid kunne følges i kundeteamets backlog.

**Comment by annerisbakk** [comment]
Denne saken kan kanskje være et godt eksempel på sak for Styringsteamet https://baksia.digdir.no/teams/styringssystem/
Team Styringssystem skal legge til rette for at «alt henger sammen» i avdelingen mtp hvilke verktøy vi benytter for å styre og utføre arbeid i avdelingen, og sørge for at alle team dokumenterer sine prosesser og ansvarsområder helhetlig. Dette vil f.eks. være å legge til rette for bruk av OKR som metodikk og dokumentere hvordan man gjør det.
@SnorreTE
